### PR TITLE
Migrate history.min.js cdn from unpkg to cdnjs

### PR DESCRIPTION
**Pull request by Richienb**

### CODE REVIEW

**Comment by Olian04** [comment]
Thank you for the PR! 
May i ask why you think we should use cdnjs over unpkg?

**Comment by Richienb** [comment]
1. Cdnjs is much faster than unpkg
2. Decrease cross domain fetches
3. Stops unexpected behaviour caused by versions changing

**Comment by Olian04** [comment]
> 1. Cdnjs is much faster than unpkg

Do you have any statistics to back that up? Because [according to unpkg](https://unpkg.com/#/about): "The fast, global infrastructure that powers unpkg is generously donated by Cloudflare".

> 2. Decrease cross domain fetches

Why is this an issue? Each asset is fetched individually either way, are they not? 

> 3. Stops unexpected behaviour caused by versions changing

True, the version should be locked down. But this can be done with unpkg as well, like this: `unpkg.com/:package@:version`. I will do it as soon as I've decided if we want to move to cdnjs or stay with unpkg

**Comment by Richienb** [comment]
> Do you have any statistics to back that up? Because according to unpkg: "The fast, global infrastructure that powers unpkg is generously donated by Cloudflare".

Cdnjs **is** CloudFlare. It is the only one on the [CloudFlare blog](https://blog.cloudflare.com/cdnjs-the-fastest-javascript-repo-on-the-web/).

> Why is this an issue? Each asset is fetched individually either way, are they not?

This is how a request is usually handled by a browser in the **old code**:

1. Connect to cdnjs
1. Load files
    1. showdown.min.js
    1. github-markdown.min.css
1. Connect to unpkg
1. Load files
    1. history.min.js

This is how a request can be handled by making all the cdn urls the same:

1. Connect to cdnjs
1. Load files
    1. showdown.min.js
    1. github-markdown.min.css
    1. history.min.js

**Comment by Olian04** [comment]
Alright, you've convinced me.

**Pull request merged**
